version: "3.3"

services:
  math-academy-client:
    container_name: math-academy-client
    restart: always
    image: node:20.19.0
    env_file:
      - .env.local
    ports:
      - 4006:3000
    environment:
      - PORT=3000
    volumes:
      - ./:/usr/src/math-academy-client
    working_dir: /usr/src/math-academy-client
    networks:
      - client-network
    command: bash -c "npm install --legacy-peer-deps && npm run build && npm run start"

networks:
  client-network:
    driver: bridge