export enum GroupType {
  DTM = "DTM",
  SAT = "SAT",
  MILLIY_SERTIFIKAT = "MILLIY_SERTIFIKAT",
  ATTESTATSIYA = "ATTESTATSIYA",
}

export enum GroupStatus {
  ACTIVE = "ACTIVE",
  INACTIVE = "INACTIVE",
  ARCHIVED = "ARCHIVED",
}