export enum TestType {
  DTM = "DTM",
  SAT = "SAT",
  MILLIY_SERTIFIKAT = "MILLIY_SERTIFIKAT",
  ATTESTATSIYA = "ATTESTATSIYA",
  MAJBURIY_BLOK = "MAJBURIY_BLOK",
  DTM_GROUP = "DTM_GROUP",
  SAT_GROUP = "SAT_GROUP",
  MILLIY_GROUP = "MILLIY_GROUP",
  ATTESTATSIYA_GROUP = "ATTESTATSIYA_GROUP",
  MAJBURIY_BLOK_GROUP = "MAJBURIY_BLOK_GROUP",
}

export enum TestAccess {
  PUBLIC = "PUBLIC",
  PREMIUM = "PREMIUM",
  GROUP = "GROUP",
}

export enum TestStatus {
  DRAFT = "DRAFT",
  PUBLISHED = "PUBLISHED",
  ARCHIVED = "ARCHIVED",
}

export enum TestBlock {
  MANDATORY = "MANDATORY",
  ELECTIVE = "ELECTIVE",
}